on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v1.21.4
        with:
          version: latest
          args: release --clean
          workdir: ./weather

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
