name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and Install
        run: |
          make install INSTALL_PATH=$HOME/go/bin
          export PATH=$HOME/go/bin:$PATH

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        #env:
         #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
