name: Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Initialize Go Module
        run: go mod init weather

      - name: Determine Installation Path
        id: determine_install_path
        run: |
          if [ -d "/usr/local/bin" ]; then
            INSTALL_PATH="/usr/local/bin"
          elif [ -d "/usr/bin" ]; then
            INSTALL_PATH="/usr/bin"
          else
            INSTALL_PATH="$HOME/go/bin"
          fi
          echo "INSTALL_PATH=$INSTALL_PATH" >> $GITHUB_ENV

      - name: Build and Install
        run: |
          make install INSTALL_PATH="$INSTALL_PATH"
          export PATH="$INSTALL_PATH:$PATH"

      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
